In [25]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from pathlib import Path

In [26]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

In [27]:
from data import *
from data.base_dataset import *
from data.pdbbind_dataset import *
from model import *

In [28]:
device = torch.device("cuda:2" if torch.cuda.is_available() else "cpu")

In [29]:
path = Path('../../data')

In [30]:
input_nc = 24
bs = 16

tfms = transforms.Compose([Center(),
                           Rotate(90),
                           Channel(['C'], input_nc, 1.0, 1.4),
                           Channel(['O'], input_nc, 1.0, 1.4),
                           Channel(['N'], input_nc, 1.0, 1.4),
                           ToTensor()])
class Option:
    csvfile = path/'refined_set.csv'
    dataroot = '../../../2018/refined-set/'
    channels = 'cno'
    grid_size = 20
    grid_spacing = 1
    rvdw = 1.4
    filter_kd = True
    rotate = 10

opt = Option()
ds = PdbBindDataset()
ds.initialize(opt)
dl = torch.utils.data.DataLoader(ds, batch_size=bs,
                                 shuffle=True, num_workers=0)

In [31]:
data = next(iter(dl))

In [41]:
data['grids'][0,1].cpu().numpy()

array([[[  5.58753044e-12,   9.74631487e-12,   1.69861902e-11, ...,
           1.35584877e-11,   7.25541849e-12,   3.88178378e-12],
        [  8.34865510e-12,   1.52607926e-11,   2.81034085e-11, ...,
           2.35950148e-11,   1.18552945e-11,   5.99842398e-12],
        [  1.20341515e-11,   2.30775399e-11,   4.49991155e-11, ...,
           3.98938660e-11,   1.87573290e-11,   8.97693031e-12],
        ..., 
        [  1.07303055e-12,   1.61826108e-12,   2.40507614e-12, ...,
           1.82942550e-12,   1.17084120e-12,   7.38742401e-13],
        [  6.62359056e-13,   9.64117675e-13,   1.38034029e-12, ...,
           1.03228537e-12,   6.88893387e-13,   4.52415883e-13],
        [  4.08562073e-13,   5.75539616e-13,   7.96807065e-13, ...,
           5.89528426e-13,   4.08117984e-13,   2.77888823e-13]],

       [[  8.80229223e-12,   1.58719704e-11,   2.86406454e-11, ...,
           2.11185514e-11,   1.08280052e-11,   5.57742741e-12],
        [  1.34843248e-11,   2.56099586e-11,   4.91091612e-1

In [35]:
np.max()

1.9862977

In [15]:
model = KDeepModel(input_nc=6)
model.to(device)

NameError: name 'KDeepModel' is not defined

In [29]:
import torch.optim as optim

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

In [57]:
for param_group in optimizer.param_groups:
    param_group['lr'] = 0.0001

In [ ]:
for epoch in range(10):
    running_loss = 0
    for i, data in enumerate(dl, 0):
        grids = data['grids'].to(device)
        affinities = data['affinity'].to(device)
        optimizer.zero_grad()

        # forward + backward + optimize
        outputs = model(grids)
        loss = criterion(outputs, affinities)
        loss.backward()
        optimizer.step()

        # print statistics
        running_loss += loss.item()
        if i % 20 == 19:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 20))
            running_loss = 0.0

[1,    20] loss: 42.319
[1,    40] loss: 45.145
[1,    60] loss: 45.195
[1,    80] loss: 38.745
[1,   100] loss: 42.507
[1,   120] loss: 42.891
[2,    20] loss: 45.096
[2,    40] loss: 40.623
[2,    60] loss: 42.159
[2,    80] loss: 40.413
[2,   100] loss: 43.612
[2,   120] loss: 46.234
[3,    20] loss: 45.709
[3,    40] loss: 38.737
[3,    60] loss: 41.660
[3,    80] loss: 49.065
[3,   100] loss: 39.815
[3,   120] loss: 45.227
[4,    20] loss: 43.844
[4,    40] loss: 43.751
[4,    60] loss: 45.393
[4,    80] loss: 42.424
[4,   100] loss: 43.655
[4,   120] loss: 39.146
[5,    20] loss: 40.133
[5,    40] loss: 43.738
[5,    60] loss: 46.688
[5,    80] loss: 44.534
[5,   100] loss: 42.289
[5,   120] loss: 40.027
[6,    20] loss: 42.493
[6,    40] loss: 45.166
[6,    60] loss: 42.097
[6,    80] loss: 43.195
[6,   100] loss: 41.787
[6,   120] loss: 47.753
[7,    20] loss: 46.517
[7,    40] loss: 41.264
[7,    60] loss: 39.224
[7,    80] loss: 44.188
[7,   100] loss: 45.179
[7,   120] loss:

In [55]:
outputs

tensor([[10.8296],
        [10.4283],
        [ 9.4874],
        [ 9.2714],
        [ 9.8149]], device='cuda:1', grad_fn=<AddmmBackward>)

In [56]:
affinities

tensor([[ 8.5685],
        [ 4.7105],
        [ 2.8134],
        [ 5.8091],
        [16.1181]], device='cuda:1')